# Generated by Django 3.2.8 on 2021-10-10 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Nombre de usuario')),
                ('password', models.CharField(max_length=256, verbose_name='Contraseña')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('dirección', models.CharField(max_length=30, verbose_name='Direccion')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('telefono', models.IntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('idcentro', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('dirección', models.CharField(max_length=30, verbose_name='Direccion')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('telefono', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCliente', models.CharField(max_length=30, verbose_name='Solicitud')),
                ('ciudad', models.CharField(max_length=30, verbose_name='Descripcion')),
                ('FinalizedState', models.BooleanField(default=True)),
                ('idcentro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitud', to='mujerApp.centro')),
                ('iduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitud', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
