# Generated by Django 3.2.8 on 2021-10-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mujerApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dirección',
        ),
        migrations.AddField(
            model_name='user',
            name='direccion',
            field=models.CharField(default=False, max_length=30, verbose_name='direccion'),
            preserve_default=False,
        ),
    ]
