# Generated by Django 3.2.8 on 2021-10-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mujerApp', '0002_auto_20211014_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cedula',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='cedula'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=256, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True, verbose_name='username'),
        ),
    ]
