# Generated by Django 3.2.8 on 2021-10-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mujerApp', '0004_auto_20211021_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centro',
            name='idcentro',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
