# Generated by Django 3.2.8 on 2021-10-21 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mujerApp', '0005_alter_centro_idcentro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centro',
            old_name='dirección',
            new_name='direccion',
        ),
    ]
