# Generated by Django 3.2.8 on 2021-10-24 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mujerApp', '0008_alter_solicitud_ciudad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='iduser',
        ),
    ]
