# Generated by Django 3.2.8 on 2021-10-24 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mujerApp', '0010_alter_solicitud_idcentro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='idcentro',
        ),
    ]
