# Generated by Django 3.2.8 on 2021-10-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mujerApp', '0014_solicitud_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='cedula',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='centro',
            name='nombre',
            field=models.CharField(max_length=70, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='centro',
            name='telefono',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='FinalizedState',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='cedula',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='cedula'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.BigIntegerField(default=0),
        ),
    ]
